name: Setup ENV Action
description: Preparing all of needs environment

runs:
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: 8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Cache Gradle Package
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

  using: composite