name: Build Debug Workflow
on:
  workflow_call:
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build Apk Release
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --full-stacktrace
      - name: Sign Apk Release
        id: sign_apk
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.KEYSTORE }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          keystore_password: ${{ secrets.STORE_PASSWORD }}
          key_password: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Apk Release
        uses: actions/upload-artifact@v2
        with:
          name: Apk Release Artifact
          path: app/build/outputs/apk/release