name: Build Debug Workflow
on:
  workflow_call:
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build App Debug Execution
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --full-stacktrace