name: Build Debug Workflow
on:
  workflow_call:
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build Apk Release
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --full-stacktrace
      - name: Sign Apk Release
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Apk Release
        uses: actions/upload-artifact@v2
        with:
          name: Apk Release Artifact
          path: ${{steps.sign_app.outputs.signedReleaseFile}}