name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml
  build:
    needs: test
    uses: ./.github/workflows/build-debug-workflow.yml