name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  setup-env:
    uses: ./.github/workflows/setup-env-workflow.yml
  build:
    needs: setup-env
    runs-on: ubuntu-20.04
    steps:
      - name : Gradle Wrapper
        run : gradle wrapper
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace