name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml
  android-lint:
    uses: ./.github/workflows/lint-android-workflow.yml
  build:
    needs:
      - test
      - android-lint
    uses: ./.github/workflows/build-debug-workflow.yml