name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    needs: setup-env
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/setup-env
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace