name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - run: chmod +x ./gradlew
      - name: Test
        run: ./gradlew clean test --full-stacktrace
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - run: chmod +x ./gradlew
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace