name: Main Push Workflow
on:
  push:
    branches:
      - main
jobs:
  test-coverage:
    uses: ./.github/workflows/test-coverage-workflow.yml
  build-apk:
    uses: ./.github/workflows/build-release-workflow.yml