name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    setup-env:
      uses: arieftb/meowvie-android-app/.github/workflows/setup-env-workflow.yml@MADE
    steps:
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace