name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  setup-env:
    uses: ./.github/workflows/setup-env-workflow.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace