name: Main Pull Request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    call-setup-env-workflow-in-local-repo:
      uses: ./.github/workflows/setup-env-workflow.yml
    steps:
      - name: Build App Debug
        run: ./gradlew clean assembleDebug --full-stacktrace